### PR TITLE
Added API link to READMe, no other changes

### PR DESCRIPTION
**Pull request by bkennedy06**

### CODE REVIEW

**Comment by ljbarker** [comment]
Thanks for clearing it up.

**Comment by adnunn19** [comment]
Thanks for adding that

**Comment by bkennedy06** [comment]
> Thanks for adding that

Pleasure, glad to keep everyone on the same page

**Comment by eswenke** [comment]
Good looks Bryce, this is perfect. Free, easy to use API to enhance our application.

**Comment by cdslaugh2814** [comment]
Cool, I'll look at the API when I can.

**Pull request merged**
