### PR TITLE
Test suite

### PR DESCRIPTION
**Pull request by eswenke**

### CODE REVIEW

**Comment by adnunn19** [comment]
LGTM

**Comment by ljbarker** [comment]
Looks like bugs worked out, thanks!

**Comment by bkennedy06** [comment]
Super helpful, glad you caught the address bug in the promises

**Comment by eswenke** [comment]
Thanks Bryce, the localhost to azure pipeline was a doozy, but we worked it out!

**Comment by cdslaugh2814** [comment]
Azure keeps making things hard. Hopefully, this is the last of the conflicts it caused.

**Pull request merged**
