### PR TITLE
Added functionality of search bar to retain information put inside after pressing enter

### PR DESCRIPTION
**Pull request by adnunn19**
Title is exactly what I added

### CODE REVIEW

**Review by bkennedy06 — APPROVED** [review]
Big Phat W

**Comment by ljbarker** [comment]
Great change, adds a much better user experience.

**Comment by adnunn19** [comment]
> Great change, adds a much better user experience.

Thanks, going to use this to store information into server data so we can utilize our API to do a search lookup in our recipe database.

**Comment by cdslaugh2814** [comment]
One step closer to a full search bar.

**Comment by eswenke** [comment]
Looks good! We'll work together on this once the API is implemented to implement filters along with the search.

**Pull request merged**
