### PR TITLE
Azure develop

### PR DESCRIPTION
**Pull request by cdslaugh2814**
makes changes to set up the backend for azure. This includes changes to the yml file for the backend and changes to the front end to communicate to the new backend.

### CODE REVIEW

**Comment by adnunn19** [comment]
Looks good to me

**Comment by ljbarker** [comment]
Thanks, looks good based on the canvas page about CI/CD!

**Comment by cdslaugh2814** [comment]
Yeah, this is the stuff for the CICD assignment

**Comment by bkennedy06** [comment]
Glad you got this up and running, no more local host!

**Comment by cdslaugh2814** [comment]
Local host be gone!

**Comment by eswenke** [comment]
Thank you chris! This looks good, the CI/CD is a big step in direction of a fully fledged web application! Good integration of the new links, as well.

**Pull request merged**
